server:   # Biz bu projemizde 'ConfigServer' modülünde kaydediyoruz ayarlarımızı. ConfigServerGit'i sadece bir kez deneme amaçlı kullandık (config dosyalarını Git'te tutma olayı).
  port: 8888 # Örn: http://localhost:8888/auth-micro-service-application.yml  (öncesinde ConfigServer modülü ayağa kaldırılmalı, ve auth-micro-service)

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server
  profiles:
    active: native # config files will be stored on the local system.
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
