server:
  port: 8888

spring:
  zipkin:
    service:
      name: config-server-git
    base-url: ${ZIPKIN_URL} # http://localhost:9411
    enabled: true
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ahmetkarahasanoglu/config-server-repo-1.git"
          default-label: main  # main branch
          skip-ssl-validation: true
          username: ahmetkarahasanoglu
          password: ${GIT_JAVA6_KEY}