spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"  # configserver modülü içindeki...
  application:
    name: elastic-service-application # bu dosyanın içinde - config ayarları.