server:
  port: 9092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/SaleDB
  jpa:
    hibernate:
      ddl-auto: update

authservice:
  bunu-biz-yazdik:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}
