server:
  port: 9100

spring:
  security:
    user:
      name: muhammethoca
      password: 12345 # Giriş yapmak için browser'da: localhost:9100 ya da localhost:9100/login . Kullanıcı adı ve şifre gir. -> sonra localhost:9100/swagger-ui/index.html (swagger konsolu açılır)
  zipkin:
    service:
      name: elastic-service
    base-url: http://localhost:9411
    enabled: true
  elasticsearch:
    uris: http://localhost:9200

security:
  secret-key: ${JAVA_SECRETKEY}
  issuer: ${JAVA6_ISSUER}